#ifndef _DEVCOM_ERROR_
#define _DEVCOM_ERROR_


/*******************全局错误码 begin**********************/
#define DEV_COM_ERROR_NONE                      0   //没有错误
#define DEV_COM_ERROR_NOINIT                    3   //没有初始化
#define DEV_COM_ERROR_CONNECT		            7	//连接服务器失败
#define DEV_COM_ERROR_SEND			            8	//向服务器发送失败
#define DEV_COM_ERROR_RECV			            9	//从服务器接收数据失败
#define DEV_COM_ERROR_RECV_TIMEOUT		        10	//从服务器接收数据超时
#define DEV_COM_ERROR_DATA                      11  //网络上接收到的数据异常
#define DEV_COM_ERROR_ORDER                     12  //调用次序错误
#define DEV_COM_ERROR_PARAMETER                 17  //参数错误
#define DEV_COM_ERROR_SUPPORT                   23  //不支持该功能
#define DEV_COM_ERROR_ALLOC_RESOURCE            41  //资源分配错误
#define DEV_COM_ERROR_NOENOUGH_BUF              43  //缓冲区太小
#define DEV_COM_ERROR_CREATESOCKET              44  //创建SOCKET出错
#define DEV_COM_ERROR_SETSOCKET                 45  //设置SOCKET出错
#define DEV_COM_ERROR_MAXNUM                    46  //达到最大数量
#define DEV_COM_ERROR_BINDSOCKET    			72	//绑定套接字失败
#define DEV_COM_ERROR_SOCKETCLOSE   			73	//socket连接中断，此错误通常是由于连接中断或目的地不可达

//认证错误码
#define DEV_COM_ERROR_AUTHENTICATION_SUCCESS                     500  //认证成功
#define DEV_COM_ERROR_AUTHENTICATION_FAIL                        501  //认证失败
#define DEV_COM_ERROR_AUTHENTICATION_CMD_ERROR                   502  //非法命令
#define DEV_COM_ERROR_AUTHENTICATION_DATA_INVALID                503  //协议解析失败
#define DEV_COM_ERROR_AUTHENTICATION_DEV_ID_INVALID              504  //DevID非法
#define DEV_COM_ERROR_AUTHENTICATION_QUERY_AUTHCODE_FAIL         505  //平台查询验证码失败
#define DEV_COM_ERROR_AUTHENTICATION_QUERY_REDIS_FAIL            506  //平台查询redis失败
#define DEV_COM_ERROR_AUTHENTICATION_SESSION_KEY_INVALID         507  //SessionKey无效
#define DEV_COM_ERROR_AUTHENTICATION_ENCRYPT_FAIL                508  //协议加密失败
#define DEV_COM_ERROR_AUTHENTICATION_QUERY_DATA_ERROR            509  //查询Das或Stun信息失败
#define DEV_COM_ERROR_AUTHENTICATION_MASTERKEY_INVALID           510  //masterkey非法
#define DEV_COM_ERROR_AUTHENTICATION_SESSION_KEY_INVALID_NOT          //暂不用
#define DEV_COM_ERROR_STUN_INVALID_AUTHENTICATION                512  //查询stun认证失败
#define DEV_COM_ERROR_DAS_INVALID_AUTHENTICATION                 513  //查询das认证失败
#define DEV_COM_ERROR_CODE_ERROR                                 514  //交互流程错误
#define DEV_COM_ERROR_LBS_UPDATE_REDIS_FAIL                      515  //平台更新设备信息失败

//语音对讲错误码
#define DEV_COM_ERROR_PARSING_FAIL               600  //解析消息失败
#define DEV_COM_ERROR_CHECK_TOKEN                601  //验证token失败

//萤石微内核错误码
#define DEV_COM_ERROR_EZDEVSDK_INDEX                100000
#define DEV_COM_ERROR_EZDEVSDK_INTERNAL             (DEV_COM_ERROR_EZDEVSDK_INDEX + 1)  //内部错误
#define DEV_COM_ERROR_EZDEVSDK_INVALD_CALL          (DEV_COM_ERROR_EZDEVSDK_INDEX + 2)  //调用流程有误
#define DEV_COM_ERROR_EZDEVSDK_PARAMS_INVALID       (DEV_COM_ERROR_EZDEVSDK_INDEX + 3)  //参数非法
#define DEV_COM_ERROR_EZDEVSDK_BUFFER_TOO_SMALL     (DEV_COM_ERROR_EZDEVSDK_INDEX + 4)  //缓冲区大小不足
#define DEV_COM_ERROR_EZDEVSDK_DATA_LEN_RANGE       (DEV_COM_ERROR_EZDEVSDK_INDEX + 5)  //数据大小超出范围
#define DEV_COM_ERROR_EZDEVSDK_MEMORY               (DEV_COM_ERROR_EZDEVSDK_INDEX + 6)  //内存异常
#define DEV_COM_ERROR_EZDEVSDK_JSON_INVALID         (DEV_COM_ERROR_EZDEVSDK_INDEX + 7)  //非法的json数据
#define DEV_COM_ERROR_EZDEVSDK_JSON_FORMAT          (DEV_COM_ERROR_EZDEVSDK_INDEX + 8)  //json数据有误
#define DEV_COM_ERROR_EZDEVSDK_EXTEND_NO_FIND       (DEV_COM_ERROR_EZDEVSDK_INDEX + 9)  //信令路由找不到对应的注册领域
#define DEV_COM_ERROR_EZDEVSDK_EXTEND_FULL          (DEV_COM_ERROR_EZDEVSDK_INDEX + 10) //扩展注册已满
#define DEV_COM_ERROR_EZDEVSDK_EXTEND_EXISTED       (DEV_COM_ERROR_EZDEVSDK_INDEX + 11) //扩展已经注册
#define DEV_COM_ERROR_EZDEVSDK_QUEUE_FULL           (DEV_COM_ERROR_EZDEVSDK_INDEX + 12) //消息队列已满
#define DEV_COM_ERROR_EZDEVSDK_VALUE_LOAD           (DEV_COM_ERROR_EZDEVSDK_INDEX + 13) //获取设备数据失败
#define DEV_COM_ERROR_EZDEVSDK_VALUE_SAVE           (DEV_COM_ERROR_EZDEVSDK_INDEX + 14) //保存数据至设备失败
#define DEV_COM_ERROR_EZDEVSDK_MSG_STOP_DISTRIBUTE  (DEV_COM_ERROR_EZDEVSDK_INDEX + 15) //设备正在停止,上层消息停止下发
#define DEV_COM_ERROR_EZDEVSDK_MSG_DEFLATE_FAIL     (DEV_COM_ERROR_EZDEVSDK_INDEX + 16) //报文解压失败
#define DEV_COM_ERROR_EZDEVSDK_MSG_INFLATE_FAIL     (DEV_COM_ERROR_EZDEVSDK_INDEX + 17) //报文压缩失败
#define DEV_COM_ERROR_EZDEVSDK_INS_FULL             (DEV_COM_ERROR_EZDEVSDK_INDEX + 18) //客户端数量达到上限

#define DEV_COM_ERROR_EZDEVSDK_NET_INDEX            100300
#define DEV_COM_ERROR_EZDEVSDK_NET_CREATE           (DEV_COM_ERROR_EZDEVSDK_NET_INDEX + 1)  ///< 创建socket失败
#define DEV_COM_ERROR_EZDEVSDK_NET_CONNECT          (DEV_COM_ERROR_EZDEVSDK_NET_INDEX + 2)  ///< 网络连接失败
#define DEV_COM_ERROR_EZDEVSDK_NET_DISCONNECTED     (DEV_COM_ERROR_EZDEVSDK_NET_INDEX + 3)  ///< 网络连接断开
#define DEV_COM_ERROR_EZDEVSDK_NET_TRANSMIT         (DEV_COM_ERROR_EZDEVSDK_NET_INDEX + 4)  ///< 数据传输失败
#define DEV_COM_ERROR_EZDEVSDK_NET_DNS              (DEV_COM_ERROR_EZDEVSDK_NET_INDEX + 5)  ///< 域名解析失败

#define DEV_COM_ERROR_EZDEVSDK_LBS_INDEX                100600
#define DEV_COM_ERROR_EZDEVSDK_NET_AUTHCODE_MISMATCH    (DEV_COM_ERROR_EZDEVSDK_LBS_INDEX + 1)  ///< 验证码不一致
#define DEV_COM_ERROR_EZDEVSDK_NET_INVALID_CALL         (DEV_COM_ERROR_EZDEVSDK_LBS_INDEX + 2)  ///< 和服务器的交互流程有问题
#define DEV_COM_ERROR_EZDEVSDK_NET_INVALID_DATA         (DEV_COM_ERROR_EZDEVSDK_LBS_INDEX + 3)  ///< 服务器收到错误数据
#define DEV_COM_ERROR_EZDEVSDK_NET_DEVID_MISMATCH       (DEV_COM_ERROR_EZDEVSDK_LBS_INDEX + 4)  ///< devid不一致
#define DEV_COM_ERROR_EZDEVSDK_NET_MASTERKEY_MISMATCH   (DEV_COM_ERROR_EZDEVSDK_LBS_INDEX + 5)  ///< masterkey不一致
#define DEV_COM_ERROR_EZDEVSDK_NET_SESSIONKEY_MISMATCH  (DEV_COM_ERROR_EZDEVSDK_LBS_INDEX + 6)  ///< sessionkey不一致
#define DEV_COM_ERROR_EZDEVSDK_NET_INVALID_DEV          (DEV_COM_ERROR_EZDEVSDK_LBS_INDEX + 7)  ///< 无效设备
#define DEV_COM_ERROR_EZDEVSDK_NET_SERVER_CRYPTO        (DEV_COM_ERROR_EZDEVSDK_LBS_INDEX + 8)  ///< 服务器加解密失败
#define DEV_COM_ERROR_EZDEVSDK_NET_GET_DATA             (DEV_COM_ERROR_EZDEVSDK_LBS_INDEX + 9)  ///< 获取das或者stun信息失败
#define DEV_COM_ERROR_EZDEVSDK_NET_SERVER_EXCEPTION     (DEV_COM_ERROR_EZDEVSDK_LBS_INDEX + 10) ///< 服务器内部异常
#define DEV_COM_ERROR_EZDEVSDK_NET_CHECK_SESSIONKEY_FAIL (DEV_COM_ERROR_EZDEVSDK_LBS_INDEX +  11) ///< sessionkey验证失败
#define DEV_COM_ERROR_EZDEVSDK_NET_SIGN_CHECK_FAIL       (DEV_COM_ERROR_EZDEVSDK_LBS_INDEX + 12)  ///< auth_i校验sign失败、申请device id校验sign失败(可能验证码出错)

#define DEV_COM_ERROR_EZDEVSDK_SECRETKEY_INDEX              100900
#define DEV_COM_ERROR_EZDEVSDK_SECRETKEY_DECRYPT_FAIL       (DEV_COM_ERROR_EZDEVSDK_SECRETKEY_INDEX + 0)    ///< 申请secretkey报文平台解密失败
#define DEV_COM_ERROR_EZDEVSDK_SECRETKEY_OVERFLOW_WINDOWS   (DEV_COM_ERROR_EZDEVSDK_SECRETKEY_INDEX + 1)    ///< 申请secretkey请求不在窗口期
#define DEV_COM_ERROR_EZDEVSDK_SECRETKEY_NO_USER            (DEV_COM_ERROR_EZDEVSDK_SECRETKEY_INDEX + 2)    ///< 设备未绑定用户
#define DEV_COM_ERROR_EZDEVSDK_SECRETKEY_SN_NOT_EXIST       (DEV_COM_ERROR_EZDEVSDK_SECRETKEY_INDEX + 3)    ///< 设备不存在
#define DEV_COM_ERROR_EZDEVSDK_SECRETKEY_AGAIN              (DEV_COM_ERROR_EZDEVSDK_SECRETKEY_INDEX + 4)    ///< 设备重复申请

#define DEV_COM_ERROR_EZDEVSDK_DAS_INDEX                    101000
#define DEV_COM_ERROR_EZDEVSDK_DAS_NOSUPPORT_PROTOCOL_VER   (DEV_COM_ERROR_EZDEVSDK_DAS_INDEX + 1)  ///< 不支持的协议版本
#define DEV_COM_ERROR_EZDEVSDK_DAS_CLIENT_ID_INVALID        (DEV_COM_ERROR_EZDEVSDK_DAS_INDEX + 2)  ///< 不合格的客户端标识符
#define DEV_COM_ERROR_EZDEVSDK_DAS_SERVER_UNUSABLE          (DEV_COM_ERROR_EZDEVSDK_DAS_INDEX + 3)  ///< 服务端不可用(服务器内部异常)
#define DEV_COM_ERROR_EZDEVSDK_DAS_INVALID_USERNAME         (DEV_COM_ERROR_EZDEVSDK_DAS_INDEX + 4)  ///< 无效的用户名或密码（现阶段暂不使用）
#define DEV_COM_ERROR_EZDEVSDK_DAS_UNAUTHORIZED             (DEV_COM_ERROR_EZDEVSDK_DAS_INDEX + 5)  ///< 未授权（现阶段暂不使用）
#define DEV_COM_ERROR_EZDEVSDK_DAS_SESSION_INVAILD          (DEV_COM_ERROR_EZDEVSDK_DAS_INDEX + 6)  ///< 接入会话失效
#define DEV_COM_ERROR_EZDEVSDK_DAS_FORCE_OFFLINE            (DEV_COM_ERROR_EZDEVSDK_DAS_INDEX + 7)  ///< 设备被强制下线
#define DEV_COM_ERROR_EZDEVSDK_DAS_FORCE_DEV_RISK           (DEV_COM_ERROR_EZDEVSDK_DAS_INDEX + 8)  ///< 设备被风控（黑名单）
#define DEV_COM_ERROR_EZDEVSDK_DAS_FORCE_DOMAIN_RISK        (DEV_COM_ERROR_EZDEVSDK_DAS_INDEX + 9)  ///< 领域被风控
#define DEV_COM_ERROR_EZDEVSDK_DAS_FORCE_CMD_RISK           (DEV_COM_ERROR_EZDEVSDK_DAS_INDEX + 10) ///< 指令被风控

/*******************全局错误码 end**********************/
#endif