/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: linux-x86"
#define DATE "built on: Tue Dec 13 07:37:01 2022 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','/','m','n','t','/','r',
    'e','g','s','d','i','s','k','/','h','o','m','e','/','s','h','i',
    'd','o','n','g','x','u','e','/','r','o','u','t','e','r','/','C',
    'P','E','_','1','8','0','0','_','4','G','/','1','1','2','2','/',
    'r','o','u','t','e','r','_','m','t','k','/','p','r','o','d','u',
    'c','t','/','r','o','u','t','e','r','/','.','.','/','.','.','/',
    't','o','o','l','s','-','c','h','a','i','n','/','t','o','o','l',
    'c','h','a','i','n','-','m','i','p','s','e','l','_','2','4','k',
    'c','_','g','c','c','-','5','.','4','.','0','_','m','u','s','l',
    '-','1','.','1','.','1','6','/','b','i','n','/','m','i','p','s',
    'e','l','-','o','p','e','n','w','r','t','-','l','i','n','u','x',
    '-','m','u','s','l','-','g','c','c',' ','-','E','L',' ','-','f',
    'P','I','C',' ','-','p','t','h','r','e','a','d',' ','-','W','a',
    'l','l',' ','-','O','3',' ','-','f','o','m','i','t','-','f','r',
    'a','m','e','-','p','o','i','n','t','e','r',' ',' ','-','D','O',
    'P','E','N','S','S','L','_','U','S','E','_','N','O','D','E','L',
    'E','T','E',' ','-','D','L','_','E','N','D','I','A','N',' ','-',
    'D','O','P','E','N','S','S','L','_','P','I','C',' ','-','D','N',
    'D','E','B','U','G','\0'
};
