#ifndef __HPR_ATOMIC_H__
#define __HPR_ATOMIC_H__

#include "HPR_Config.h"
#include "HPR_Types.h"

#if defined(OS_WINDOWS)
    typedef LONG HPR_ATOMIC_T;
#elif defined(OS_POSIX)
    typedef HPR_UINT32 HPR_ATOMIC_T;
#endif

HPR_DECLARE HPR_VOID CALLBACK HPR_AtomicInc(HPR_ATOMIC_T* pVal);
HPR_DECLARE HPR_VOID CALLBACK HPR_AtomicDec(HPR_ATOMIC_T* pVal);
HPR_DECLARE HPR_UINT32 CALLBACK HPR_AtomicAdd(HPR_ATOMIC_T* pDst, HPR_ATOMIC_T nVal);
HPR_DECLARE HPR_UINT32 CALLBACK HPR_AtomicSet(HPR_ATOMIC_T* pDst, HPR_ATOMIC_T nVal);
HPR_DECLARE HPR_UINT32 CALLBACK HPR_AtomicCas(HPR_ATOMIC_T* pDst, HPR_ATOMIC_T nWith, HPR_ATOMIC_T nCmp);
HPR_DECLARE HPR_VOIDPTR CALLBACK HPR_AtomicCasPtr(HPR_VOIDPTR* pDst, HPR_VOIDPTR pWith, HPR_VOIDPTR pCmp);

#endif // __HPR_ATOMIC_H__
